--[[
Spells:
GENERATED BY *printSpells.py* - DO NOT EDIT MANUALLY!
]]--


kps.spells = {}


-- Draenic Potions
kps.spells.potion = {}
kps.spells.potion.draenicIntellectPotion = kps.Spell.Item.fromId(156426) -- Draenic Intellect Potion
kps.spells.potion.draenicAgilityPotion = kps.Spell.Item.fromId(156577) -- Draenic Agility Potion
kps.spells.potion.draenicStrengthPotion = kps.Spell.Item.fromId(156428) -- Draenic Strength Potion


-- Spells which require a select (cast on ground cursor)
kps.spells.ae = {}
kps.spells.ae.powerWordBarrier = kps.Spell.fromId(62618) -- Power Word: Barrier
kps.spells.ae.bindingShot = kps.Spell.fromId(109248) -- Binding Shot
kps.spells.ae.shadowfury = kps.Spell.fromId(30283) -- Shadowfury
kps.spells.ae.massDispel = kps.Spell.fromId(32375) -- Mass Dispel
kps.spells.ae.holyWordSanctify = kps.Spell.fromId(34861) -- Holy Word: Sanctify
kps.spells.ae.deathAndDecay = kps.Spell.fromId(43265) -- Death and Decay
kps.spells.ae.powerWordBarrier = kps.Spell.fromId(62618) -- Power Word: Barrier
kps.spells.ae.flamestrike = kps.Spell.fromId(2120) -- Flamestrike
kps.spells.ae.lightsHammer = kps.Spell.fromId(114158) -- Light's Hammer
kps.spells.ae.summonJadeSerpentStatue = kps.Spell.fromId(115313) -- Summon Jade Serpent Statue
kps.spells.ae.heroicLeap = kps.Spell.fromId(6544) -- Heroic Leap
kps.spells.ae.freeze = kps.Spell.fromId(33395) -- Freeze
kps.spells.ae.runeOfPower = kps.Spell.fromId(116011) -- Rune of Power
kps.spells.ae.summonBlackOxStatue = kps.Spell.fromId(115315) -- Summon Black Ox Statue
kps.spells.ae.cataclysm = kps.Spell.fromId(152108) -- Cataclysm
kps.spells.ae.earthquake = kps.Spell.fromId(61882) -- Earthquake
kps.spells.ae.rainOfFireChanneled = kps.Spell.fromId(5740) -- Rain of Fire (Channeled)
kps.spells.ae.healingRain = kps.Spell.fromId(73920) -- Healing Rain
kps.spells.ae.explosiveTrap = kps.Spell.fromId(13813) -- Explosive Trap
kps.spells.ae.iceTrap = kps.Spell.fromId(13809) -- Ice Trap
kps.spells.ae.defile = kps.Spell.fromId(152280) -- Defile
kps.spells.ae.metamorphosis = kps.Spell.fromId(187827) -- Metamorphosis
kps.spells.ae.starfall = kps.Spell.fromId(191034) -- Starfall
kps.spells.ae.efflorescence = kps.Spell.fromId(145205) -- Efflorescence
kps.spells.ae.infernalStrike = kps.Spell.fromId(189110) -- Infernal Strike
kps.spells.ae.bilescourgeBombers = kps.Spell.fromId(267211) -- Bilescourge Bombers


-- Crowd Control Spells
kps.spells.cc = {}
kps.spells.cc.mindControl = kps.Spell.fromId(605) -- Mind Control
kps.spells.cc.entanglingRoots = kps.Spell.fromId(339) -- Entangling Roots
kps.spells.cc.cyclone = kps.Spell.fromId(33786) -- Cyclone
kps.spells.cc.iceTrap = kps.Spell.fromId(13809) -- Ice Trap
kps.spells.cc.polymorph = kps.Spell.fromId(118) -- Polymorph
kps.spells.cc.polymorphBlackCat = kps.Spell.fromId(61305) -- Polymorph (BlackCat)
kps.spells.cc.polymorphPig = kps.Spell.fromId(28272) -- Polymorph (Pig)
kps.spells.cc.polymorphRabbit = kps.Spell.fromId(61721) -- Polymorph (Rabbit)
kps.spells.cc.polymorphTurkey = kps.Spell.fromId(61780) -- Polymorph (Turkey)
kps.spells.cc.polymorphTurtle = kps.Spell.fromId(28271) -- Polymorph (Turtle)
kps.spells.cc.fear = kps.Spell.fromId(5782) -- Fear
kps.spells.cc.howlOfTerror = kps.Spell.fromId(5484) -- Howl of Terror
kps.spells.cc.hex = kps.Spell.fromId(51514) -- Hex
kps.spells.cc.sap = kps.Spell.fromId(6770) -- Sap
kps.spells.cc.blind = kps.Spell.fromId(2094) -- Blind
kps.spells.cc.repentance = kps.Spell.fromId(20066) -- Repentance


-- Nagrand Combat Mounts
kps.spells.mount = {}
kps.spells.mount.frostwolfWarWolf = kps.Spell.fromId(164222) -- Frostwolf War Wolf
kps.spells.mount.telaariTalbuk = kps.Spell.fromId(165803) -- Telaari Talbuk
kps.spells.mount.druidForm = kps.Spell.fromId(783) -- Druid Form


-- Bloodlust
kps.spells.bloodlust = {}
kps.spells.bloodlust.bloodlust = kps.Spell.fromId(2825) -- Bloodlust
kps.spells.bloodlust.heroism = kps.Spell.fromId(32182) -- Heroism
kps.spells.bloodlust.timeWarp = kps.Spell.fromId(80353) -- Time Warp
kps.spells.bloodlust.ancientHysteria = kps.Spell.fromId(90355) -- Ancient Hysteria
kps.spells.bloodlust.drumsOfRage = kps.Spell.fromId(146555) -- Drums of Rage


-- Polymorph Spells
kps.spells.poly = {}
kps.spells.poly.polymorph = kps.Spell.fromId(118) -- Polymorph
kps.spells.poly.polymorphBlackCat = kps.Spell.fromId(61305) -- Polymorph (BlackCat)
kps.spells.poly.polymorphPig = kps.Spell.fromId(28272) -- Polymorph (Pig)
kps.spells.poly.polymorphRabbit = kps.Spell.fromId(61721) -- Polymorph (Rabbit)
kps.spells.poly.polymorphTurkey = kps.Spell.fromId(61780) -- Polymorph (Turkey)
kps.spells.poly.polymorphTurtle = kps.Spell.fromId(28271) -- Polymorph (Turtle)
kps.spells.poly.hex = kps.Spell.fromId(51514) -- Hex


-- User-Priorized Spells to ignore
kps.spells.ignore = {}
kps.spells.ignore.autoAttack = kps.Spell.fromId(6603) -- Auto Attack (prevents from toggling on/off)
kps.spells.ignore.roll = kps.Spell.fromId(109132) -- Roll (Unless you want to roll off cliffs, leave this here)
kps.spells.ignore.stormEarthAndFire = kps.Spell.fromId(137639) -- Storm, Earth, and Fire (prevents you from destroying your copy as soon as you make it)
kps.spells.ignore.detox = kps.Spell.fromId(115450) -- Detox (when casting Detox without any dispellable debuffs, the cooldown resets)
kps.spells.ignore.purifyingBrew = kps.Spell.fromId(119582) -- Purifying Brew (having more than 1 chi, this can prevent using it twice in a row)
kps.spells.ignore.chiTorpedo = kps.Spell.fromId(115008) -- Chi Torpedo (same as roll)
kps.spells.ignore.flyingSerpentKick = kps.Spell.fromId(101545) -- Flying Serpent Kick (prevents you from landing as soon as you start 'flying')
kps.spells.ignore.expelHarm = kps.Spell.fromId(115072) -- Expel Harm (below 35%, brewmasters ignores cooldown on this spell)
kps.spells.ignore.breathOfFire = kps.Spell.fromId(115181) -- Breath of Fire (if you are chi capped, this can make you burn all your chi)
kps.spells.ignore.provoke = kps.Spell.fromId(115546) -- Provoke (prevents you from wasting your taunt)
kps.spells.ignore.tigereyeBrew = kps.Spell.fromId(116740) -- Tigereye Brew (prevents you from wasting your stacks and resetting your buff)
kps.spells.ignore.burningRush = kps.Spell.fromId(111400) -- warlock burning rush
kps.spells.ignore.evocation = kps.Spell.fromId(12051) -- Evocation
kps.spells.ignore.blink = kps.Spell.fromId(1953) -- Blink
kps.spells.ignore.deterrence = kps.Spell.fromId(19263) -- Deterrence
kps.spells.ignore.disengage = kps.Spell.fromId(781) -- Disengage
kps.spells.ignore.iceFloes = kps.Spell.fromId(108839) -- Ice Floes
kps.spells.ignore.felRush = kps.Spell.fromId(195072) -- Fel Rush

-- Ignore some dispellable debuff
kps.spells.ignoreDebuff = {}
kps.spells.ignoreDebuff.vampiricTouch = kps.Spell.fromId(34914)

-- Greater Draenic Flasks
kps.spells.flask = {}
kps.spells.flask.greaterDraenicAgilityFlask = kps.Spell.fromId(156064) -- Greater Draenic Agility Flask
kps.spells.flask.greaterDraenicIntellectFlask = kps.Spell.fromId(156079) -- Greater Draenic Intellect Flask
kps.spells.flask.greaterDraenicStrengthFlask = kps.Spell.fromId(156572) -- Greater Draenic Strength Flask
kps.spells.flask.greaterDraenicStaminaFlask = kps.Spell.fromId(156576) -- Greater Draenic Stamina Flask


-- Battle Rez
kps.spells.battlerez = {}
kps.spells.battlerez.rebirth = kps.Spell.fromId(20484) -- Rebirth
kps.spells.battlerez.raiseAlly = kps.Spell.fromId(61999) -- Raise Ally
kps.spells.battlerez.soulstone = kps.Spell.fromId(20707) -- Soulstone
kps.spells.battlerez.eternalGuardian = kps.Spell.fromId(126393) -- Eternal Guardian

-- Immune Heal
kps.spells.immuneHeal = {}
kps.spells.immuneHeal.misery = kps.Spell.fromId(243961) -- Misery
kps.spells.immuneHeal.caressOfDeath = kps.Spell.fromId(285213) -- Caress of Death
kps.spells.immuneHeal.embraceOfTheVoid = kps.Spell.fromId(282738) -- Embrace of the Void
kps.spells.immuneHeal.darkestDepths = kps.Spell.fromId(292127) -- Darkest Depths -- Reduces incoming healing by 100%

-- Absorption Heal
kps.spells.absorptionHeal = {}
kps.spells.absorptionHeal.necroticEmbrace = kps.Spell.fromId(244093) -- Necrotic Embrace
kps.spells.absorptionHeal.spearOfAnguish = kps.Spell.fromId(235933) -- Spear of Anguish
kps.spells.absorptionHeal.embraceOfTheEclipse = kps.Spell.fromId(233263) -- Embrace of the Eclipse
kps.spells.absorptionHeal.soulblight = kps.Spell.fromId(248396) -- Soulblight
kps.spells.absorptionHeal.chilledBlood = kps.Spell.fromId(245586) -- Chilled Blood

-- Boss Debuff (Uldir)
kps.spells.bossDebuff = {}
kps.spells.bossDebuff.deathwish = kps.Spell.fromId(274271) -- Magic
kps.spells.bossDebuff.grievousAxe = kps.Spell.fromId(284781) -- Roi Rastakhan Dazar'alor


-- ignore Aura Buff
kps.spells.immuneDamage = {}
kps.spells.immuneDamage.divineShield = kps.Spell.fromId(642)
kps.spells.immuneDamage.dispersion = kps.Spell.fromId(47585)
kps.spells.immuneDamage.iceBlock = kps.Spell.fromId(45438)
kps.spells.immuneDamage.spellReflection = kps.Spell.fromId(216890)
kps.spells.immuneDamage.netherWard = kps.Spell.fromId(212295)
kps.spells.immuneDamage.cloakOfShadows = kps.Spell.fromId(31224)
kps.spells.immuneDamage.aspectOfTheTurtle = kps.Spell.fromId(186265)
kps.spells.immuneDamage.antiMagicShell = kps.Spell.fromId(48707)
kps.spells.immuneDamage.netherwalk = kps.Spell.fromId(196555)
kps.spells.immuneDamage.greaterFade = kps.Spell.fromId(213602)

-- Spells Clipping while casting
kps.spells.clippingSpell = {}
kps.spells.clippingSpell.mindFlay = kps.Spell.fromId(15407)
-- Spells Castable while casting other spells
kps.spells.castableSpell = {}
kps.spells.castableSpell.fireBlast = kps.Spell.fromId(108853)
kps.spells.castableSpell.combustion = kps.Spell.fromId(190319)
kps.spells.castableSpell.searingNightmare = kps.Spell.fromId(341385)

-- AZERITE ESSENCE
kps.spells.azerite = {}
-- "The Unbound Force" -- 
kps.spells.azerite.theUnboundForce = kps.Spell.fromId(298452)
-- "Concentrated Flame" -- Each cast of Concentrated Flame deals 100% increased damage or healing. This bonus resets after every third cast.
kps.spells.azerite.concentratedFlame = kps.Spell.fromId(295373)
-- "Refreshment" -- Release all healing stored in The Well of Existence into an ally. This healing is amplified by 20%.
kps.spells.azerite.refreshment = kps.Spell.fromId(296197)
-- "Overcharge Mana" -- Overcharge your mana for 10 sec, causing each spell you cast to increase your healing by 3%, stacking.
kps.spells.azerite.overchargeMana = kps.Spell.fromId(296072)
-- "Refreshment" -- Release all healing stored in The Well of Existence into an ally. This healing is amplified by 20%.
kps.spells.azerite.theWellOfExistence = kps.Spell.fromId(296138)
-- "Memory of Lucid Dreams" -- Increasing your [Mana][Energy][Maelstrom] generation rate by 100% and your Leech by 0 for 15 sec.
kps.spells.azerite.memoryOfLucidDreams = kps.Spell.fromId(298357)
-- "Aegis of the Deep" -- elements protect you, reducing the damage you take from each attack by 4112 for 15 sec.
kps.spells.azerite.aegisOfTheDeep = kps.Spell.fromId(298168)
-- "Azeroth's Undying Gift" -- "Don éternel d’Azeroth" -- Reduce all damage you take by 20% for 4 sec.
kps.spells.azerite.azerothUndyingGift = kps.Spell.fromId(293019)
-- "Gardien d’Azeroth" -- "Guardian of Azeroth" -- un gardien d’Azeroth pendant 30 sec. Ce gardien empale votre cible avec des pointes d’azérite toutes les 2 s
kps.spells.azerite.guardianOfAzeroth = kps.Spell.fromId(295840)
-- "Reaping Flames" -- Burn your target with a bolt of Azerite, dealing 33385 Fire damage. If the target has less than 20% health, the cooldown is reduced by 30 sec.
kps.spells.azerite.reapingFlames = kps.Spell.fromId(310690)
-- Purifying Blast
kps.spells.azerite.purifyingBlast = kps.Spell.fromId(295337)
-- Focused Azerite Beam
kps.spells.azerite.focusedazeriteBeam = kps.Spell.fromId(295258)
-- Vitality Conduit
kps.spells.azerite.vitalityConduit = kps.Spell.fromId(296230)

-- ARMORY ITEM
kps.spells.item = {}
kps.spells.item.hyperthreadWristwraps = kps.Spell.Item.fromId(168989)
