language: python
python:
  - "2.7"
sudo: false

before_install:
  - pip install hererocks
  - hererocks /tmp/base -r^ --lua=5.2
  - export PATH=$PATH:/tmp/base/bin # Add directory with all installed binaries to PATH

script:
  - make test
  - make integration_test

notifications:
  email:
    on_success: change
    on_failure: always
